'use strict';
// Optional UI verification: install Playwright, or point EMBER_PLAYWRIGHT_PATH at an existing package.
const { chromium } = require(process.env.EMBER_PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '..');

(async () => {
  await fs.mkdir(path.join(root, '.playwright'), { recursive: true });
  const browser = await chromium.launch({ headless: true, ...(process.env.EMBER_BROWSER_PATH ? { executablePath: process.env.EMBER_BROWSER_PATH } : {}) });
  const errors = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
    const page = await context.newPage();
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await page.goto(pathToFileURL(path.join(root, 'index.html')).href);
    await page.locator('#stat-hunger').waitFor();
    await page.screenshot({ path: path.join(root, '.playwright', 'desktop.png'), fullPage: true });
    assert.equal(await page.locator('.action-card').count(), 4);
    await page.getByRole('button', { name: '工坊', exact: true }).click();
    await page.locator('[data-action="craft"][data-id="axe"]').click();
    assert.equal(await page.locator('[data-item="axe"]').count(), 1);
    const craftedSave = await page.evaluate(() => JSON.parse(localStorage.getItem('ember-wilderness-save-v1')));
    assert.equal(craftedSave.inventory.axe, 1);
    await page.reload();
    assert.equal(await page.locator('[data-item="axe"]').count(), 1);
    assert.equal(await page.locator('#game-time').textContent(), '08:30');
    await page.getByRole('button', { name: '地图', exact: true }).first().click();
    await page.locator('[data-location="forest"]').click();
    await page.locator('#map-detail [data-action="travel"]').click();
    const event = page.locator('.event-choice:not([disabled])');
    if (await event.count()) await event.last().click();
    assert.equal(await page.locator('#location-name').textContent(), '低语松林');
    await page.waitForTimeout(200);
    await page.locator('.action-card[data-action="gather"][data-id="chop"]').click();
    if (await event.count()) { await page.waitForTimeout(200); await event.last().click(); }
    const harvested = await page.evaluate(() => JSON.parse(localStorage.getItem('ember-wilderness-save-v1')));
    assert.equal(harvested.inventory.wood, 6);
    assert.equal(harvested.durability.axe, 23);
    await page.waitForTimeout(200);
    await page.locator('[data-item="berry"]').click();
    await page.locator('[data-action="use"][data-id="berry"]').click();
    const eaten = await page.evaluate(() => JSON.parse(localStorage.getItem('ember-wilderness-save-v1')));
    assert.equal(eaten.inventory.berry, 2);
    assert.ok(eaten.hunger > harvested.hunger);
    await page.getByRole('button', { name: '生存手册', exact: true }).click();
    assert.equal(await page.locator('#game-dialog').evaluate(element => element.open), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#game-dialog').evaluate(element => element.open), false);
    await page.getByRole('button', { name: '存档与设置', exact: true }).click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator('[data-command="export"]').click();
    const download = await downloadPromise;
    const downloadPath = path.join(root, '.playwright', 'exported-save.json');
    await download.saveAs(downloadPath);
    const exported = JSON.parse(await fs.readFile(downloadPath, 'utf8'));
    assert.equal(exported.time, eaten.time);
    await page.locator('#import-file').setInputFiles(downloadPath);
    await page.locator('[data-command="import-confirm"]').click();
    assert.equal(await page.locator('#game-time').textContent(), `${String(Math.floor(exported.time % 1440 / 60)).padStart(2, '0')}:${String(exported.time % 60).padStart(2, '0')}`);
    const timeBefore = exported.time;
    await page.getByRole('button', { name: '存档与设置', exact: true }).click();
    await page.locator('#import-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":99}') });
    await page.waitForFunction(() => document.querySelector('#toast-region').textContent.includes('存档不完整'));
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('ember-wilderness-save-v1')).time), timeBefore);
    await page.keyboard.press('Escape');
    await page.locator('#toast-region').evaluate(element => { element.innerHTML = ''; });
    await page.getByRole('button', { name: '地图', exact: true }).first().click();
    await page.screenshot({ path: path.join(root, '.playwright', 'map.png'), fullPage: true });
    await page.getByRole('button', { name: '工坊', exact: true }).click();
    await page.locator('[data-craft-filter="food"]').click();
    await page.screenshot({ path: path.join(root, '.playwright', 'crafting.png'), fullPage: true });
    for (const width of [390, 760, 1024, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `horizontal overflow at ${width}px`);
    }
    const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
    const mobile = await mobileContext.newPage();
    mobile.on('pageerror', error => errors.push(error.message));
    await mobile.goto(pathToFileURL(path.join(root, 'index.html')).href);
    await mobile.locator('#stat-hunger').waitFor();
    assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile horizontal overflow');
    await mobile.screenshot({ path: path.join(root, '.playwright', 'mobile.png'), fullPage: true });
    await mobile.locator('.mobile-shortcuts [data-command="bag"]').click();
    await mobile.locator('[data-item="berry"]').click();
    await mobile.locator('[data-action="use"][data-id="berry"]').click();
    const mobileSave = await mobile.evaluate(() => JSON.parse(localStorage.getItem('ember-wilderness-save-v1')));
    assert.equal(mobileSave.inventory.berry, 2);
    assert.equal(mobileSave.time, 485);

    const { state: completedJourney } = require('../tests/survival-run.cjs')(20260913);
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.getByRole('button', { name: '存档与设置', exact: true }).click();
    await page.locator('#import-file').setInputFiles({ name: 'completed.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(completedJourney)) });
    await page.locator('[data-command="import-confirm"]').click();
    assert.match(await page.locator('#dialog-title').textContent(), /天亮以后/);
    await page.screenshot({ path: path.join(root, '.playwright', 'ending.png') });
    await page.locator('[data-command="continue"]').click();
    assert.equal(await page.locator('#game-dialog').evaluate(element => element.open), false);
    let finalState = await page.evaluate(() => JSON.parse(localStorage.getItem('ember-wilderness-save-v1')));
    assert.equal(finalState.endless, true); assert.equal(finalState.status, 'playing');
    await page.getByRole('button', { name: '存档与设置', exact: true }).click();
    await page.locator('[data-command="reset"]').click();
    await page.locator('[data-command="close"]').first().click();
    assert.equal(await page.locator('#day-number').textContent(), '08');
    await page.getByRole('button', { name: '存档与设置', exact: true }).click();
    await page.locator('[data-command="reset"]').click();
    await page.locator('[data-command="restart-now"]').click();
    assert.equal(await page.locator('#day-number').textContent(), '01');
    assert.equal(await page.locator('#game-time').textContent(), '08:00');
    finalState = await page.evaluate(() => JSON.parse(localStorage.getItem('ember-wilderness-save-v1')));
    assert.equal(finalState.structures.beacon, false);

    const G = require('../game.js');
    const doomed = G.createState(12);
    while (doomed.status === 'playing') G.act(doomed, 'gather', 'rest');
    await page.getByRole('button', { name: '存档与设置', exact: true }).click();
    await page.locator('#import-file').setInputFiles({ name: 'last-page.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(doomed)) });
    await page.locator('[data-command="import-confirm"]').click();
    assert.match(await page.locator('#dialog-title').textContent(), /荒野，记住/);
    await page.locator('[data-command="read-ending"]').click();
    assert.equal(await page.locator('#game-dialog').evaluate(element => element.open), false);
    assert.equal(await page.locator('.action-card:not([disabled])').count(), 0);

    assert.deepEqual(errors, []);
    console.log('Browser smoke passed: file:// launch, crafting, movement, gathering, eating, reload, help, export/import, bad-save rejection, responsive desktop/mobile controls, victory, endless mode, reset/cancel, and death journal.');
    console.log('Screenshots saved under .playwright/.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
